import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import toast from 'react-hot-toast';

export const useExportSystem = () => {
    /**
     * Export data as a CSV file
     * @param {Array[]} data - Array of row arrays (matching headers)
     * @param {string[]} headers - Array of header strings
     * @param {string} filename - Output filename (without extension)
     */
    const exportCSV = (data, headers, filename) => {
        try {
            const csvRows = [
                headers.join(','),
                ...data.map(row => 
                    row.map(cell => {
                        const str = cell === null || cell === undefined ? '' : cell.toString();
                        return `"${str.replace(/"/g, '""')}"`;
                    }).join(',')
                )
            ];
            const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${filename}_${new Date().toISOString().slice(0, 10)}.csv`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            toast.success('CSV exported successfully');
        } catch (err) {
            console.error('CSV Export Error:', err);
            toast.error('CSV export failed');
        }
    };

    /**
     * Export data as a professional PDF report
     * @param {Array[]} data - Array of row arrays
     * @param {string[]} headers - Array of header strings
     * @param {string} title - Report title
     * @param {string} filename - Output filename (without extension)
     * @param {Object} options - Optional KPI data or additional text
     */
    const exportPDF = (data, headers, title, filename, options = {}) => {
        try {
            const doc = new jsPDF();
            const timestamp = new Date().toLocaleString();

            // 1. Branding & Header
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(22);
            doc.setTextColor(245, 158, 11); // Amber
            doc.text(title, 14, 22);
            
            doc.setFontSize(10);
            doc.setTextColor(100, 100, 100);
            doc.text(`Generated by WorkflowPro on: ${timestamp}`, 14, 30);
            
            if (options.period) {
                doc.text(`Period: ${options.period}`, 14, 35);
            }

            doc.setDrawColor(245, 158, 11);
            doc.setLineWidth(0.5);
            doc.line(14, 40, 196, 40);

            let currentY = 50;

            // 2. Summary Section (Optional)
            if (options.kpis) {
                doc.setFontSize(14);
                doc.setTextColor(31, 41, 55);
                doc.text('Key Performance Metrics', 14, currentY);
                
                autoTable(doc, {
                    startY: currentY + 5,
                    head: [['Metric', 'Value', 'Status']],
                    body: options.kpis,
                    headStyles: { fillColor: [31, 41, 55], textColor: [255, 255, 255] },
                    styles: { fontSize: 10 },
                    theme: 'striped',
                    margin: { left: 14, right: 14 }
                });
                currentY = doc.lastAutoTable.finalY + 15;
            }

            // 3. AI Insights (Optional)
            if (options.insights) {
                doc.setFontSize(12);
                doc.setTextColor(16, 185, 129); // Green
                doc.text('Strategic Insights:', 14, currentY);
                doc.setFontSize(10);
                doc.setTextColor(75, 85, 99);
                const splitInsights = doc.splitTextToSize(options.insights, 180);
                doc.text(splitInsights, 14, currentY + 7);
                currentY += (splitInsights.length * 5) + 15;
            }

            // 4. Data Table
            doc.setFontSize(14);
            doc.setTextColor(31, 41, 55);
            doc.text('Detailed Record Breakdown', 14, currentY);

            autoTable(doc, {
                startY: currentY + 5,
                head: [headers],
                body: data,
                headStyles: { fillColor: [245, 158, 11], textColor: [0, 0, 0] },
                alternateRowStyles: { fillColor: [249, 250, 251] },
                styles: { fontSize: 8, cellPadding: 3 },
                margin: { top: 10 },
                theme: 'grid'
            });

            // 5. Finalize
            doc.save(`${filename}_${new Date().toISOString().slice(0, 10)}.pdf`);
            toast.success('Professional PDF report exported successfully');
        } catch (err) {
            console.error('PDF Export Error:', err);
            toast.error('PDF export failed');
        }
    };

    return { exportCSV, exportPDF };
};
